keys:
  - &sky ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIG56OdAD9r6wWd+ag1R+neANX1KSdpl/h8JkYVCVdNRi

  - &cherry age1scn08ur8vv3r97k2l4q3j2jarq6gfpnz4n2mzx96hzvj8rxcefzq3ypl0z

creation_rules:
  - path_regex: ^secrets/sky\.yaml$
    key_groups:
      - age:
        - *sky

  - path_regex: ^secrets/services/[^/]+\.yaml$
    key_groups:
      - age:
        - *sky
        - *cherry
