keys:
  - &sky ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGIyMCwBcRVn8QdhGrI/2PWY6g9cIFEGphXBG2T3FHg5

creation_rules:
  - path_regex: ^secrets/sky\.yaml$
    key_groups:
      - age:
        - *sky

  - path_regex: ^secrets/services/[^/]+\.yaml$
    key_groups:
      - age:
        - *sky
