# QoL
set -g mouse on
set -s escape-time 0
set -g default-terminal "tmux-256color"
set -sa terminal-overrides ",xterm*:Tc"

# set leader key to C‑a
unbind C-b
set -g prefix C-a
bind C-a send-prefix

# reload config (prefix + r)
bind r source-file ~/.tmux.conf \; display-message "tmux config reloaded!"

# clear screen (C-k)
bind -n C-k send-keys C-l

# panes
bind -r h select-pane -L
bind -r j select-pane -D
bind -r k select-pane -U
bind -r l select-pane -R
bind v split-window -h
bind n split-window -v
bind x kill-pane

# windows
bind w new-window -c "#{pane_current_path}"
bind n next-window
bind p previous-window

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'catppuccin/tmux#v2.1.3'

set -g @catppuccin_flavor 'frappe'

run '$HOMEBREW_PREFIX/opt/tpm/share/tpm/tpm'

setw -g window-status-format "#[bg=default,fg=white] #I:#{pane_current_command} #[default]"
setw -g window-status-current-format "#[bg=default,fg=green,bold] #I:#{pane_current_command} #[default]"

set -g status-style "bg=default"
set -g status-left ""
set -g status-right ""
